name: build-maps
run-name: build-maps
on:
  push:
    branches:
      - main
  schedule:
    # At 3:48am on Sundays in May, June, July, August, and September 
    - cron: "48 3 * 5,6,7,8,9 0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Tippecanoe
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential osmium-tool gcc g++ make libsqlite3-dev zlib1g-dev
          pip install geojson shapely
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install


      - run: curl --output vermont-latest.osm.pbf https://download.geofabrik.de/north-america/us/vermont-latest.osm.pbf

      - name: Convert municipality boundaries to GeoJSON
        run: |
          osmium export vermont-latest.osm.pbf -o vermont-latest.geojson --overwrite

      - run: tippecanoe -zg --projection=EPSG:4326 -o -f asssets/vermont.pmtiles vermont-latest.geojson

      - run: rm ./vermont-latest.osm.pbf
      - run: rm ./vermont-latest.geojson

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5