name: build-maps
run-name: build-maps
on:
  push:
    branches:
      - main
  schedule:
    # At 3:48am of May, June, July, August, and September on Sunday
    - cron: "48 3 * 5,6,7,8,9 0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: download and save data
    steps:
      - uses: actions/checkout@v3

      - run: curl --output vermont-latest.osm.pbf https://download.geofabrik.de/north-america/us/vermont-latest.osm.pbf

      - uses: systemed/tilemaker@v2.0.0
        with:
          input: vermont-latest.osm.pbf
          output: vermont.pmtiles

      - run: rm ./vermont-latest.osm.pbf

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5